# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Run Services

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0/15 * * * *'
  push:
    branches: [ "master" ]


jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - uses: actions/checkout@v3
    - name: Checkout submodules
      run: git submodule update --init --remote --merge --recursive
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'

    - run: npm i
      working-directory: "boxes"
    - run: npm run job
      working-directory: "boxes"

